development:
  adapter: postgresql
  encoding: unicode
  database: send_development
  pool: 5
  username: fruityfree
  password: ENV["DB_PASS"]
test:
  adapter: postgresql
  encoding: unicode
  database: send_test
  pool: 5
  username: fruityfree
  password: unilever
production:
  adapter: mysql2
  host: localhost
  database: send
  username: fruityfree
  password: unilever