development:
  adapter: postgresql
  encoding: unicode
  database: send_development
  pool: 5
  username: fruityfree
  password: unilever
test:
  adapter: postgresql
  encoding: unicode
  database: send_test
  pool: 5
  username: fruityfree
  password: unilever
production:
  adapter: postgresql
  encoding: unicode
  database: send_production
  pool: 5
  username: fruityfree
  password: unilever